-- ============================================================================
-- V1_1_010__e01_config_and_monitor_tables.sql
-- E组公共闭环 & E01 V1.1 增量迁移 — E01 配置与监测基础表
-- ============================================================================
-- 包含 8 张表：
--   e01_monitor_point          监测点位
--   e01_monitor_plan           监测计划
--   e01_monitor_plan_item      监测计划条目
--   e01_monitor_batch          监测批次
--   e01_monitor_sample         监测样品
--   e01_factor_definition      因子定义
--   e01_standard_version       标准版本
--   e01_standard_limit         标准限值
-- ============================================================================

CREATE TABLE IF NOT EXISTS e01_monitor_point (
    id BIGINT NOT NULL AUTO_INCREMENT,
    point_code VARCHAR(80) NOT NULL,
    point_name VARCHAR(160) NOT NULL,
    source_point_name VARCHAR(255) NULL,
    chainage VARCHAR(60) NULL,
    segment_code VARCHAR(80) NULL,
    segment_name VARCHAR(160) NULL,
    engineering_object_type VARCHAR(80) NULL,
    engineering_object_id VARCHAR(100) NULL,
    engineering_object_name VARCHAR(255) NULL,
    longitude DECIMAL(11,8) NULL,
    latitude DECIMAL(10,8) NULL,
    coordinate_system VARCHAR(40) NULL,
    coordinate_source_type VARCHAR(30) NOT NULL DEFAULT 'NONE',
    coordinate_source_document_id BIGINT NULL,
    coordinate_verification_status VARCHAR(30) NOT NULL DEFAULT 'NOT_PROVIDED',
    coordinate_verified_at DATETIME(6) NULL,
    coordinate_verified_by BIGINT NULL,
    coordinate_accuracy DECIMAL(10,3) NULL,
    gis_feature_id VARCHAR(96) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
    effective_from DATETIME(6) NULL,
    effective_to DATETIME(6) NULL,
    active_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    data_nature VARCHAR(20) NOT NULL,
    is_demo TINYINT(1) NOT NULL DEFAULT 0,
    verification_status VARCHAR(30) NOT NULL DEFAULT 'PENDING_REVIEW',
    effective_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    effective_at DATETIME(6) NULL,
    effective_by BIGINT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_e01_point_code (point_code),
    KEY idx_e01_point_gis (gis_feature_id),
    CONSTRAINT fk_e01_point_coordinate_doc FOREIGN KEY (coordinate_source_document_id) REFERENCES document_record(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_e01_point_gis FOREIGN KEY (gis_feature_id) REFERENCES gis_feature(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_e01_point_longitude CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
    CONSTRAINT ck_e01_point_latitude CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_e01_point_coordinate_pair CHECK ((longitude IS NULL AND latitude IS NULL) OR (longitude IS NOT NULL AND latitude IS NOT NULL)),
    CONSTRAINT ck_e01_point_nature CHECK ((data_nature='demo' AND is_demo=1) OR (data_nature IN ('formal','platform_calc') AND is_demo=0)),
    CONSTRAINT ck_e01_point_effective CHECK (effective_status IN ('DRAFT','PENDING_REVIEW','EFFECTIVE','INVALID'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS e01_monitor_plan (
    id BIGINT NOT NULL AUTO_INCREMENT,
    plan_code VARCHAR(80) NOT NULL,
    plan_year SMALLINT NOT NULL,
    quarter_code CHAR(7) NOT NULL,
    frequency_code VARCHAR(30) NOT NULL DEFAULT 'QUARTERLY',
    testing_provider_org_id BIGINT NULL,
    testing_provider_name VARCHAR(160) NOT NULL,
    owner_department_org_id BIGINT NULL,
    owner_department_name VARCHAR(160) NOT NULL,
    plan_document_id BIGINT NULL,
    version_no VARCHAR(30) NOT NULL,
    plan_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    data_nature VARCHAR(20) NOT NULL,
    is_demo TINYINT(1) NOT NULL DEFAULT 0,
    verification_status VARCHAR(30) NOT NULL DEFAULT 'PENDING_REVIEW',
    effective_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    effective_at DATETIME(6) NULL,
    effective_by BIGINT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_e01_plan_code (plan_code),
    CONSTRAINT fk_e01_plan_provider FOREIGN KEY (testing_provider_org_id) REFERENCES org_unit(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_e01_plan_owner FOREIGN KEY (owner_department_org_id) REFERENCES org_unit(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_e01_plan_document FOREIGN KEY (plan_document_id) REFERENCES document_record(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_e01_plan_quarter CHECK (quarter_code REGEXP '^[0-9]{4}-Q[1-4]$'),
    CONSTRAINT ck_e01_plan_year_quarter CHECK (CAST(LEFT(quarter_code,4) AS UNSIGNED)=plan_year),
    CONSTRAINT ck_e01_plan_frequency CHECK (frequency_code='QUARTERLY'),
    CONSTRAINT ck_e01_plan_nature CHECK ((data_nature='demo' AND is_demo=1) OR (data_nature IN ('formal','platform_calc') AND is_demo=0)),
    CONSTRAINT ck_e01_plan_effective CHECK (effective_status IN ('DRAFT','PENDING_REVIEW','EFFECTIVE','INVALID'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS e01_monitor_plan_item (
    id BIGINT NOT NULL AUTO_INCREMENT,
    plan_id BIGINT NOT NULL,
    point_id BIGINT NOT NULL,
    monitor_category VARCHAR(20) NOT NULL,
    planned_sample_at DATETIME(6) NULL,
    planned_factor_scope VARCHAR(1000) NULL,
    execution_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    data_nature VARCHAR(20) NOT NULL,
    is_demo TINYINT(1) NOT NULL DEFAULT 0,
    effective_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    effective_at DATETIME(6) NULL,
    effective_by BIGINT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_e01_plan_item (plan_id, point_id, monitor_category),
    CONSTRAINT fk_e01_plan_item_plan FOREIGN KEY (plan_id) REFERENCES e01_monitor_plan(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_e01_plan_item_point FOREIGN KEY (point_id) REFERENCES e01_monitor_point(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_e01_plan_item_category CHECK (monitor_category IN ('WATER','AIR','NOISE')),
    CONSTRAINT ck_e01_plan_item_nature CHECK ((data_nature='demo' AND is_demo=1) OR (data_nature IN ('formal','platform_calc') AND is_demo=0)),
    CONSTRAINT ck_e01_plan_item_effective CHECK (effective_status IN ('DRAFT','PENDING_REVIEW','EFFECTIVE','INVALID'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS e01_monitor_batch (
    id BIGINT NOT NULL AUTO_INCREMENT,
    batch_code VARCHAR(80) NOT NULL,
    plan_id BIGINT NULL,
    quarter_code CHAR(7) NOT NULL,
    report_no VARCHAR(120) NULL,
    testing_provider_org_id BIGINT NULL,
    testing_provider_name VARCHAR(160) NOT NULL,
    sample_start_at DATETIME(6) NOT NULL,
    sample_end_at DATETIME(6) NOT NULL,
    report_issued_at DATETIME(6) NULL,
    received_at DATETIME(6) NULL,
    source_document_id BIGINT NULL,
    source_file_id BIGINT NULL,
    ingestion_job_id BIGINT NULL,
    batch_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    idempotency_key VARCHAR(160) NOT NULL,
    data_nature VARCHAR(20) NOT NULL,
    is_demo TINYINT(1) NOT NULL DEFAULT 0,
    effective_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    effective_at DATETIME(6) NULL,
    effective_by BIGINT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_e01_batch_code (batch_code),
    UNIQUE KEY uk_e01_batch_idempotency (idempotency_key),
    KEY idx_e01_batch_quarter (quarter_code, effective_status, data_nature),
    CONSTRAINT fk_e01_batch_plan FOREIGN KEY (plan_id) REFERENCES e01_monitor_plan(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_e01_batch_provider FOREIGN KEY (testing_provider_org_id) REFERENCES org_unit(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_e01_batch_document FOREIGN KEY (source_document_id) REFERENCES document_record(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_e01_batch_file FOREIGN KEY (source_file_id) REFERENCES file_asset(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_e01_batch_job FOREIGN KEY (ingestion_job_id) REFERENCES data_ingestion_job(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_e01_batch_quarter CHECK (quarter_code REGEXP '^[0-9]{4}-Q[1-4]$'),
    CONSTRAINT ck_e01_batch_time CHECK (sample_start_at<=sample_end_at),
    CONSTRAINT ck_e01_batch_status CHECK (batch_status IN ('DRAFT','PARSED','VALIDATED','PENDING_REVIEW','EFFECTIVE','REJECTED','INVALID')),
    CONSTRAINT ck_e01_batch_nature CHECK ((data_nature='demo' AND is_demo=1) OR (data_nature IN ('formal','platform_calc') AND is_demo=0)),
    CONSTRAINT ck_e01_batch_effective CHECK (effective_status IN ('DRAFT','PENDING_REVIEW','EFFECTIVE','INVALID'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS e01_monitor_sample (
    id BIGINT NOT NULL AUTO_INCREMENT,
    sample_code VARCHAR(100) NOT NULL,
    batch_id BIGINT NOT NULL,
    plan_item_id BIGINT NULL,
    point_id BIGINT NOT NULL,
    monitor_category VARCHAR(20) NOT NULL,
    sampled_at DATETIME(6) NOT NULL,
    sample_end_at DATETIME(6) NULL,
    planned_sample_at_snapshot DATETIME(6) NULL,
    planned_actual_variance_minutes INT NULL,
    sample_no VARCHAR(100) NULL,
    idempotency_key VARCHAR(180) NOT NULL,
    sample_status VARCHAR(30) NOT NULL DEFAULT 'PENDING_REVIEW',
    void_reason VARCHAR(500) NULL,
    duplicate_of_sample_id BIGINT NULL,
    raw_record_document_id BIGINT NULL,
    data_nature VARCHAR(20) NOT NULL,
    is_demo TINYINT(1) NOT NULL DEFAULT 0,
    verification_status VARCHAR(30) NOT NULL DEFAULT 'PENDING_REVIEW',
    effective_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    effective_at DATETIME(6) NULL,
    effective_by BIGINT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_e01_sample_code (sample_code),
    UNIQUE KEY uk_e01_sample_idempotency (idempotency_key),
    KEY idx_e01_sample_kpi (sampled_at, monitor_category, sample_status, effective_status, data_nature, is_demo),
    CONSTRAINT fk_e01_sample_batch FOREIGN KEY (batch_id) REFERENCES e01_monitor_batch(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_e01_sample_plan_item FOREIGN KEY (plan_item_id) REFERENCES e01_monitor_plan_item(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_e01_sample_point FOREIGN KEY (point_id) REFERENCES e01_monitor_point(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_e01_sample_duplicate FOREIGN KEY (duplicate_of_sample_id) REFERENCES e01_monitor_sample(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_e01_sample_raw_doc FOREIGN KEY (raw_record_document_id) REFERENCES document_record(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_e01_sample_category CHECK (monitor_category IN ('WATER','AIR','NOISE')),
    CONSTRAINT ck_e01_sample_status CHECK (sample_status IN ('VALID','PENDING_REVIEW','VOID','DUPLICATE')),
    CONSTRAINT ck_e01_sample_time CHECK (sample_end_at IS NULL OR sampled_at<=sample_end_at),
    CONSTRAINT ck_e01_sample_duplicate CHECK ((sample_status='DUPLICATE' AND duplicate_of_sample_id IS NOT NULL) OR sample_status<>'DUPLICATE'),
    CONSTRAINT ck_e01_sample_nature CHECK ((data_nature='demo' AND is_demo=1) OR (data_nature IN ('formal','platform_calc') AND is_demo=0)),
    CONSTRAINT ck_e01_sample_effective CHECK (effective_status IN ('DRAFT','PENDING_REVIEW','EFFECTIVE','INVALID'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS e01_factor_definition (
    id BIGINT NOT NULL AUTO_INCREMENT,
    factor_code VARCHAR(80) NOT NULL,
    factor_name VARCHAR(160) NOT NULL,
    monitor_category VARCHAR(20) NOT NULL,
    default_unit VARCHAR(60) NULL,
    effective_from DATETIME(6) NULL,
    effective_to DATETIME(6) NULL,
    data_nature VARCHAR(20) NOT NULL,
    is_demo TINYINT(1) NOT NULL DEFAULT 0,
    verification_status VARCHAR(30) NOT NULL DEFAULT 'PENDING_REVIEW',
    effective_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    effective_at DATETIME(6) NULL,
    effective_by BIGINT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_e01_factor_code (factor_code),
    CONSTRAINT ck_e01_factor_category CHECK (monitor_category IN ('WATER','AIR','NOISE')),
    CONSTRAINT ck_e01_factor_nature CHECK ((data_nature='demo' AND is_demo=1) OR (data_nature IN ('formal','platform_calc') AND is_demo=0)),
    CONSTRAINT ck_e01_factor_effective CHECK (effective_status IN ('DRAFT','PENDING_REVIEW','EFFECTIVE','INVALID'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS e01_standard_version (
    id BIGINT NOT NULL AUTO_INCREMENT,
    standard_code VARCHAR(100) NOT NULL,
    standard_name VARCHAR(255) NOT NULL,
    version_no VARCHAR(80) NOT NULL,
    issuing_authority VARCHAR(255) NULL,
    applicable_from DATETIME(6) NULL,
    applicable_to DATETIME(6) NULL,
    source_document_id BIGINT NULL,
    data_nature VARCHAR(20) NOT NULL,
    is_demo TINYINT(1) NOT NULL DEFAULT 0,
    verification_status VARCHAR(30) NOT NULL DEFAULT 'PENDING_REVIEW',
    effective_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    effective_at DATETIME(6) NULL,
    effective_by BIGINT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_e01_standard_version (standard_code, version_no),
    CONSTRAINT fk_e01_standard_document FOREIGN KEY (source_document_id) REFERENCES document_record(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_e01_standard_nature CHECK ((data_nature='demo' AND is_demo=1) OR (data_nature IN ('formal','platform_calc') AND is_demo=0)),
    CONSTRAINT ck_e01_standard_effective CHECK (effective_status IN ('DRAFT','PENDING_REVIEW','EFFECTIVE','INVALID'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS e01_standard_limit (
    id BIGINT NOT NULL AUTO_INCREMENT,
    standard_version_id BIGINT NOT NULL,
    factor_id BIGINT NOT NULL,
    applicable_scene VARCHAR(255) NULL,
    limit_operator VARCHAR(10) NOT NULL,
    limit_value_raw VARCHAR(100) NOT NULL,
    limit_value_num DECIMAL(24,10) NULL,
    unit VARCHAR(60) NOT NULL,
    period_description VARCHAR(255) NULL,
    data_nature VARCHAR(20) NOT NULL,
    is_demo TINYINT(1) NOT NULL DEFAULT 0,
    verification_status VARCHAR(30) NOT NULL DEFAULT 'PENDING_REVIEW',
    effective_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    effective_at DATETIME(6) NULL,
    effective_by BIGINT NULL,
    PRIMARY KEY (id),
    KEY idx_e01_limit_standard_factor (standard_version_id, factor_id),
    CONSTRAINT fk_e01_limit_standard FOREIGN KEY (standard_version_id) REFERENCES e01_standard_version(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_e01_limit_factor FOREIGN KEY (factor_id) REFERENCES e01_factor_definition(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_e01_limit_operator CHECK (limit_operator IN ('<','<=','=','>=','>')),
    CONSTRAINT ck_e01_limit_nature CHECK ((data_nature='demo' AND is_demo=1) OR (data_nature IN ('formal','platform_calc') AND is_demo=0)),
    CONSTRAINT ck_e01_limit_effective CHECK (effective_status IN ('DRAFT','PENDING_REVIEW','EFFECTIVE','INVALID'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
