-- ESG Demo V0.4 database migration script
-- Generation only. Do not execute without human approval.
-- Target: MySQL 8.4.9 / luoyi_esg
-- Preconditions: restore and verify the V0.3 backup first.

USE `luoyi_esg`;
SET NAMES utf8mb4;

-- V0.4 Migration Step 1
-- Purpose: Add the client-entered rectification completion fields.
-- Rollback: Stop the migration and restore the pre-migration snapshot; no destructive reverse SQL is included here.
ALTER TABLE `e_rectification_task`
  ADD COLUMN `rectification_completed_date` DATE NULL
    COMMENT 'Client-entered actual rectification completion date; never generated by the system',
  ADD COLUMN `rectification_completed_by` BIGINT NULL
    COMMENT 'User who entered the rectification completion date';

-- V0.4 Migration Step 2
-- Purpose: Link the completion submitter to the existing user account table.
-- Rollback: Stop the migration and restore the pre-migration schema snapshot after dependency review.
ALTER TABLE `e_rectification_task`
  ADD CONSTRAINT `fk_e_rect_task_completed_by`
  FOREIGN KEY (`rectification_completed_by`)
  REFERENCES `user_account` (`id`)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT;

-- V0.4 Migration Step 3
-- Purpose: Add project ownership for project-level closure queries; legacy rows remain nullable.
-- Rollback: Stop reads of the new field and restore the schema snapshot after dependency review.
ALTER TABLE `e_closure_case`
  ADD COLUMN `project_id` BIGINT NULL
    COMMENT 'Project ownership; legacy rows may remain NULL';

-- V0.4 Migration Step 4
-- Purpose: Add project ownership to approval facts; legacy rows remain nullable.
-- Rollback: Stop reads of the new field and restore the schema snapshot after dependency review.
ALTER TABLE `compliance_procedure`
  ADD COLUMN `project_id` BIGINT NULL
    COMMENT 'Project ownership; new API writes must provide this value';

-- V0.4 Migration Step 5
-- Purpose: Add project ownership to permit facts; legacy rows remain nullable.
-- Rollback: Stop reads of the new field and restore the schema snapshot after dependency review.
ALTER TABLE `permit_record`
  ADD COLUMN `project_id` BIGINT NULL
    COMMENT 'Project ownership; new API writes must provide this value';

-- V0.4 Migration Step 6
-- Purpose: Add source and record-time metadata while preserving V0.3 payment_rate semantics.
-- Rollback: Stop reads of the new metadata fields and restore the schema snapshot after dependency review.
ALTER TABLE `biz_worker_payment_summary`
  ADD COLUMN `source_type` VARCHAR(32) NULL
    COMMENT 'Data source type, such as finance system or manual entry',
  ADD COLUMN `record_date` DATE NULL
    COMMENT 'Actual entry or source record date; not derived from updated_at',
  ADD COLUMN `created_at` DATETIME NULL
    COMMENT 'Technical creation time';

-- V0.4 Migration Step 7
-- Purpose: Create the only new V0.4 business fact table for special-plan approvals.
-- Rollback: Stop all references and restore the pre-migration snapshot after dependency review.
CREATE TABLE `special_plan_approval` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT NOT NULL
    COMMENT 'Project ownership; required for every new fact',
  `risk_point_id` BIGINT NOT NULL
    COMMENT 'Reference to safety_risk_point.id',
  `plan_code` VARCHAR(80) NOT NULL
    COMMENT 'Project-scoped special-plan code',
  `plan_name` VARCHAR(255) NOT NULL
    COMMENT 'Special-plan name',
  `risk_level` VARCHAR(50) NOT NULL
    COMMENT 'Existing project risk-level value; no new levels are defined here',
  `approval_status` VARCHAR(40) NOT NULL
    COMMENT 'Existing project approval-status value',
  `approval_date` DATE NULL
    COMMENT 'Approval completion date',
  `approval_file_id` BIGINT NULL
    COMMENT 'Reference to file_asset.id',
  `source_doc_ref` VARCHAR(255) NULL
    COMMENT 'Source document reference',
  `data_nature` VARCHAR(20) NOT NULL DEFAULT 'demo'
    COMMENT 'demo/formal/platform_calc',
  `is_demo` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_0900_ai_ci
  COMMENT='ESG risk special-plan approval facts';

-- V0.4 Migration Step 8
-- Purpose: Add the approved special-plan uniqueness and query indexes.
-- Rollback: Stop new-table reads and restore the pre-migration snapshot after dependency review.
ALTER TABLE `special_plan_approval`
  ADD UNIQUE KEY `uk_special_plan_project_code` (`project_id`, `plan_code`),
  ADD KEY `idx_special_plan_risk_point` (`risk_point_id`),
  ADD KEY `idx_special_plan_status` (`project_id`, `approval_status`),
  ADD KEY `idx_special_plan_date` (`project_id`, `approval_date`),
  ADD KEY `idx_special_plan_level` (`project_id`, `risk_level`);

-- V0.4 Migration Step 9
-- Purpose: Enforce the approved risk-point relationship for special plans.
-- Rollback: Stop special-plan writes and restore the pre-migration snapshot after orphan checks.
ALTER TABLE `special_plan_approval`
  ADD CONSTRAINT `fk_special_plan_risk_point`
  FOREIGN KEY (`risk_point_id`)
  REFERENCES `safety_risk_point` (`id`)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT;

-- V0.4 Migration Step 10
-- Purpose: Enforce the approved file-reference relationship for special-plan evidence.
-- Rollback: Stop file-reference writes and restore the pre-migration snapshot after orphan checks.
ALTER TABLE `special_plan_approval`
  ADD CONSTRAINT `fk_special_plan_approval_file`
  FOREIGN KEY (`approval_file_id`)
  REFERENCES `file_asset` (`id`)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT;

-- Intentionally excluded from this script:
-- 1. G04 case-domain CHECK expansion, because it requires a separately approved constraint change.
-- 2. Historical data mapping and Demo data changes.
-- 3. KPI view, API contract, API paths, and front-end changes.
